
"SELECT \r\n"
+"	csp.`obecnyStan` as `trybPieca`\r\n"
+"	,csp.`zasobnik` as `zasobnik`\r\n"
+"	,ccpv2.`zasobnikMax` as `zasobnikMax`\r\n"
+"    ,ccpv2.`stdTempZadana` as `piecZadana`\r\n"
+"    ,ccpv2.`stdTempZadzialania` as `piecZadzialanie`\r\n"
+"    ,ccpv2.`stdGrzaniePodawanie` as `grzaniePodawanie`\r\n"
+"    ,ccpv2.`stdGrzaniePrzerwa` as `grzaniePrzerwa`\r\n"
+"    ,ccpv2.`stdPodtrzymaniePodawanie` as `podtrzymaniePodawanie`\r\n"
+"    ,ccpv2.`stdPodtrzymaniePrzerwa` as `podtrzymaniePrzerwa`\r\n"
+"	,CAST(avg(tempCO.`value`) AS DECIMAL(5,2)) as `tempCO`\r\n"
+"	,CAST(avg(tempCWO.`value`) AS DECIMAL(5,2)) as `tempCWO`\r\n"
+"	,CAST(avg(tempPowietrza.`value`) AS DECIMAL(5,2)) as `tempPowietrza`\r\n"
+"FROM \r\n"
+"	`node-red`.`current-state-piec` csp\r\n"
+"	CROSS JOIN `node-red`.`current-config-piec-v2` ccpv2\r\n"
+"	CROSS JOIN thermometers thTempCO\r\n"
+"		LEFT JOIN temperatures tempCO\r\n"
+"			ON thTempCO.serialId = tempCO.sensorId\r\n"
+"	\r\n"
+"	CROSS JOIN thermometers thTempCWO	\r\n"
+"		LEFT JOIN temperatures tempCWO\r\n"
+"			ON thTempCWO.serialId = tempCWO.sensorId\r\n"
+"\r\n"
+"	CROSS JOIN thermometers thTempPowietrza	\r\n"
+"		LEFT JOIN temperatures tempPowietrza\r\n"
+"			ON thTempPowietrza.serialId = tempPowietrza.sensorId\r\n"
+"\r\n"
+"WHERE \r\n"
+"	thTempCO.friendlyName = 'CO'\r\n"
+"	AND tempCO.`timestamp` > DATE_ADD(now(),INTERVAL -5 MINUTE)\r\n"
+"	AND thTempCWO.friendlyName = 'Piec-kociol'\r\n"
+"	AND tempCWO.`timestamp` > DATE_ADD(now(),INTERVAL -5 MINUTE)\r\n"
+"	AND thTempPowietrza.friendlyName = 'Pokoj'\r\n"
+"	AND tempPowietrza.`timestamp` > DATE_ADD(now(),INTERVAL -5 MINUTE)"